### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by christianbundy** [buchanae/chet#1]
I'm probably just dense, but could you give me a rundown of how to use this? A genome browser definitely sounds interesting, but I didn't seen any instructions on how to check it out. Cheers!

**Comment by buchanae** [comment]
This project is in it's really (seriously) early stages, so there is a lot of work to do before this is useable.

Honestly I didn't expect anyone to find it, but I am really excited to find that someone is interested!

That said, if you want to try out the development version, I am happy to help you get running.  The dead simple version is...
1. clone the repository
2. open "app/index.html" in your browser (e.g. using File -> Open File... in Firefox)

...or you can install node.js and run "node scripts/web-server.js" and go to "//localhost:8000/app/index.html"

If you're in need of a mature genome browser immediately, see http://gmod.org/wiki/GBrowse

**Comment by christianbundy** [comment]
Awesome, thanks – I was just looking to see which other developers were on GitHub in Corvallis (there aren't many of us) and seeing what they were working on. Saw "Genome Browser" and was super curious. I'll check it out, thanks man – have a kickass Wednesday.
